#!/bin/zsh

# Define the source and destination directories
SOURCE_DIR="/_site/notes"
DEST_DIR="../danielvoicu.dev/notes"

# Get the absolute paths of source and destination directories
SOURCE_ABS="$(cd "$(dirname "$SOURCE_DIR")" && pwd)/$(basename "$SOURCE_DIR")"
DEST_ABS="$(cd "$(dirname "$PWD")" && pwd)/$(basename "$DEST_DIR")"

# Print a message to indicate the start of the copying process
echo "Copying files from $SOURCE_ABS to $DEST_ABS ..."

# Copy the entire source directory to the destination directory
cp -rv "$SOURCE_ABS" "$DEST_ABS"

# Print a message to indicate the completion of the copying process
echo "Copying completed successfully."

# Exit the script
exit 0